### ISSUE TITLE
Keep translations just for the dev docs, for internal contributing guidelines

### ISSUE THREAD

**Issue by tobiasmcnulty** [django/django-docs-translations#14]
While investigating https://github.com/django/djangoproject.com/issues/868 I noticed that some of the translated contributing guidelines pages for previous releases are being selected by Google as the canonical version of the page for that version, instead of the dev docs as we hoped. I'm not sure if this is feasible or not, but if possible it would be nice to keep translations of the internals subsection of the docs only for the `dev` release and exclude it in `robots.txt` for all other versions.

![screenshot 2019-02-28 09 37 34](https://user-images.githubusercontent.com/160132/53574470-b196ba80-3b3d-11e9-8d12-35aa4cb17479.png)

As things are right now, we are confusing Google by telling it that the canonical version of a translated internals page is one that doesn't even exist, for languages other than English:

![screenshot 2019-02-28 09 47 33](https://user-images.githubusercontent.com/160132/53574602-e73ba380-3b3d-11e9-8078-d27f2302f007.png)

Alternatively, I guess we could modify djangoproject.com to make the canonical version of internals URLs for languages other than english point to the canonical version, rather than dev?

What would be best / easiest?

**Comment by m-aciek** [comment]
I think rationale for having `dev` docs only in English are that this is bleeding edge documentation and is being pushed publicly at the same time as new strings are being pushed to Transifex to be translated. Therefore new content would not be translated and would be confusing readers. (Am I right, @claudep?)

Having said that I am for the alternative solution -- making rel:canonicals for translations set to canonical versions instead of `dev`.

**Comment by claudep** [comment]
I'm not sure to understand all of this, but yes, what m-aciek said is right. We don't translate dev docs and don't plan to.

**Comment by tobiasmcnulty** [comment]
Closing in favor of https://github.com/django/djangoproject.com/issues/874
